
export const GET_CURRENT_MOVIE = 'app/EditMoviePage/GET_CURRENT_MOVIE';
export const GET_CURRENT_MOVIE_SUCCESS = 'app/EditMoviePage/GET_CURRENT_MOVIE_SUCCESS';
export const GET_CURRENT_MOVIE_ERROR = 'app/EditMoviePage/GET_CURRENT_MOVIE_ERROR';

export const EDIT_CURRENT_MOVIE = 'app/EditMoviePage/EDIT_CURRENT_MOVIE';
export const EDIT_CURRENT_MOVIE_SUCCESS = 'app/EditMoviePage/EDIT_CURRENT_MOVIE_SUCCESS';
export const EDIT_CURRENT_MOVIE_ERROR = 'app/EditMoviePage/EDIT_CURRENT_MOVIE_ERROR';
